repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v1.11.0
    hooks:
      - id: pyupgrade
        args: ['--py36-plus']
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
      - id: black
        args: ['.']
        language_version: python3.7
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.3
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-json
      - id: check-yaml
      - id: flake8
        args: ['--append-config=./backend/app/.flake8']
