language: python
env:
  - SECRET_KEY=testsecretkey ALLOWED_HOSTS=localhost,app,backend-app DB_HOST=backend-db
    POSTGRES_DB=app POSTGRES_USER=app_user POSTGRES_PASSWORD=testpassword
    MAILGUN_API_KEY=TEST TOKEN_TTL_HOURS=168 CORS_ORIGIN_WHITELIST=localhost,app

python:
  - "3.6"

node_js:
  - "11.7.0"

services:
  - docker

before_script:
  - cd frontend && yarn && cd ..
  - pip install docker-compose
  - pip install pipenv
  - pipenv lock -r > requirements.pip
  - pipenv lock --dev -r >> requirements.pip

script:
  - cd frontend && yarn test && cd ..
  - docker-compose run backend-app sh -c "pytest --disable-pytest-warnings && flake8"