# Generated by Django 2.1.5 on 2019-01-14 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Composer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("born", models.DateField(null=True)),
                ("died", models.DateField(null=True)),
                ("era", models.CharField(max_length=255)),
            ],
        )
    ]
