# Generated by Django 2.1.5 on 2019-01-15 05:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import core.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]

    operations = [
        migrations.CreateModel(
            name="Composer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("born", models.DateField(null=True)),
                ("died", models.DateField(null=True)),
                ("is_alive", models.BooleanField(default=False)),
                ("era", models.CharField(max_length=255)),
                ("short_name", models.CharField(blank=True, max_length=30)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Piece",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("catalog", models.CharField(blank=True, max_length=255)),
                (
                    "composer",
                    models.ManyToManyField(related_name="pieces", to="core.Composer"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Sheet",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                ("format", models.CharField(max_length=255)),
                ("type", models.CharField(blank=True, max_length=255)),
                ("file", models.FileField(upload_to=core.models.sheet_file_path)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="piece",
            name="files",
            field=models.ManyToManyField(related_name="pieces", to="core.Sheet"),
        ),
        migrations.AddField(
            model_name="piece",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
