# Generated by Django 2.1.5 on 2019-01-14 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="composer",
            name="is_alive",
            field=models.BooleanField(default=False),
        )
    ]
