# Generated by Django 2.1.5 on 2019-01-14 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0002_composer_is_alive")]

    operations = [
        migrations.AddField(
            model_name="composer",
            name="short_name",
            field=models.CharField(blank=True, max_length=30),
        )
    ]
