# Generated by Django 2.1.5 on 2019-01-14 06:56

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0003_composer_short_name")]

    operations = [
        migrations.CreateModel(
            name="Sheet",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                ("format", models.CharField(max_length=255)),
                ("file", models.FileField(upload_to=core.models.sheet_file_path)),
            ],
        )
    ]
