# Generated by Django 2.1.5 on 2019-01-20 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("core", "0003_auto_20190119_0955")]

    operations = [
        migrations.RenameField(model_name="piece", old_name="files", new_name="sheets")
    ]
