# Generated by Django 2.1.5 on 2019-01-14 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0004_sheet")]

    operations = [
        migrations.AddField(
            model_name="sheet",
            name="type",
            field=models.CharField(blank=True, max_length=255),
        )
    ]
