# Generated by Django 2.1.5 on 2019-02-01 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0005_instrument")]

    operations = [
        migrations.AddField(
            model_name="piece",
            name="instruments",
            field=models.ManyToManyField(
                related_name="instruments", to="core.Instrument"
            ),
        )
    ]
