# Generated by Django 2.1.5 on 2019-01-14 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0005_sheet_type")]

    operations = [
        migrations.CreateModel(
            name="Piece",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("catalog", models.CharField(blank=True, max_length=255)),
                (
                    "composer",
                    models.ManyToManyField(
                        null=True, related_name="pieces", to="core.Composer"
                    ),
                ),
            ],
        )
    ]
