# Generated by Django 2.1.5 on 2019-05-15 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("core", "0006_piece_instruments")]

    operations = [
        migrations.RenameField(
            model_name="sheet", old_name="file", new_name="sheet_file"
        )
    ]
