# Generated by Django 2.1.5 on 2019-01-14 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0006_piece")]

    operations = [
        migrations.AlterField(
            model_name="piece",
            name="composer",
            field=models.ManyToManyField(related_name="pieces", to="core.Composer"),
        )
    ]
